# Generated by Django 3.0.7 on 2020-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='value',
            field=models.CharField(default='light.css', max_length=200),
        ),
    ]
